/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlysinhvien;

import database.Employee;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vanli
 */
public class Admin extends javax.swing.JFrame {

//    String driver = "com.microsoft.sqlserver.jdbc.SQLServerDriver";
//    String url = " jdbc:sqlserver://localhost:1433;databaseName=QLSinhVien";
//    String user = "sa";
//    String password = "123456";
    Connection conn = null;
    Statement st;
    ResultSet rs;
    // Lưu Tiêu đề cho table
    Vector sv = new Vector();
    //Lưu dữ liệu cho table
    Vector datasv = new Vector();

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
        sv.add("ID Sinh Viên");
        sv.add("Mã Sinh Viên");
        sv.add("Tên Sinh Viên");
        sv.add("Tuổi Sinh Viên");
        sv.add("Giới Tính Sinh Viên");
        sv.add("Địa Chỉ Sinh Viên");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        lb_id = new javax.swing.JLabel();
        lb_msv = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lb_age = new javax.swing.JLabel();
        lb_gender = new javax.swing.JLabel();
        lb_address = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        txt_msv = new javax.swing.JTextField();
        txt_name = new javax.swing.JTextField();
        txt_age = new javax.swing.JTextField();
        txt_address = new javax.swing.JTextField();
        bt_add = new javax.swing.JButton();
        bt_fix = new javax.swing.JButton();
        bt_dell = new javax.swing.JButton();
        bt_show = new javax.swing.JButton();
        bt_exit_admin = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_main = new javax.swing.JTable();
        rd_boy = new javax.swing.JRadioButton();
        rd_girl = new javax.swing.JRadioButton();
        btn_timkiem = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hệ Thống Quản Lý Sinh Viên");

        lb_id.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lb_id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_id.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/id.png"))); // NOI18N
        lb_id.setText("            ID");

        lb_msv.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lb_msv.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_msv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/programming.png"))); // NOI18N
        lb_msv.setText("Mã Sinh Viên");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/name.png"))); // NOI18N
        jLabel4.setText("Tên Sinh Viên");

        lb_age.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lb_age.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_age.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/age.png"))); // NOI18N
        lb_age.setText("Tuổi Sinh Viên     ");

        lb_gender.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lb_gender.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_gender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/gender.png"))); // NOI18N
        lb_gender.setText("Giới Tính");

        lb_address.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lb_address.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_address.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/address.png"))); // NOI18N
        lb_address.setText("Địa Chỉ");

        txt_id.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt_msv.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt_name.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt_age.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt_address.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_addressActionPerformed(evt);
            }
        });

        bt_add.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bt_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/plus (1).png"))); // NOI18N
        bt_add.setText("Thêm");
        bt_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_addActionPerformed(evt);
            }
        });

        bt_fix.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bt_fix.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/edit.png"))); // NOI18N
        bt_fix.setText("Sửa");
        bt_fix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_fixActionPerformed(evt);
            }
        });

        bt_dell.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bt_dell.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete.png"))); // NOI18N
        bt_dell.setText("Xóa");
        bt_dell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_dellActionPerformed(evt);
            }
        });

        bt_show.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bt_show.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/eye.png"))); // NOI18N
        bt_show.setText("Hiển Thị");
        bt_show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_showActionPerformed(evt);
            }
        });

        bt_exit_admin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bt_exit_admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/exit.png"))); // NOI18N
        bt_exit_admin.setText("Thoát");
        bt_exit_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_exit_adminActionPerformed(evt);
            }
        });

        tb_main.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Mã Sinh Viên", "Tên Sinh Viên", "Tuổi Sinh Viên", "Giới Tính", "Địa Chỉ"
            }
        ));
        tb_main.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                none(evt);
            }
        });
        jScrollPane1.setViewportView(tb_main);

        buttonGroup1.add(rd_boy);
        rd_boy.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rd_boy.setText("Nam");

        buttonGroup1.add(rd_girl);
        rd_girl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rd_girl.setText("Nữ");

        btn_timkiem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_timkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search.png"))); // NOI18N
        btn_timkiem.setText("Tìm Kiếm");
        btn_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timkiemActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/content-management-system.png"))); // NOI18N
        jLabel1.setText("                        Chào Mừng Bạn Đến Với Hệ Thống Quản Lý Sinh Viên");
        jLabel1.setMaximumSize(new java.awt.Dimension(397, 90));
        jLabel1.setMinimumSize(new java.awt.Dimension(397, 90));
        jLabel1.setPreferredSize(new java.awt.Dimension(397, 90));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_address, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_gender, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_age, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lb_msv, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lb_id, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_age)
                            .addComponent(txt_name)
                            .addComponent(txt_msv)
                            .addComponent(txt_id)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_address))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(rd_boy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rd_girl)
                        .addGap(90, 90, 90)))
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(bt_add)
                        .addGap(18, 18, 18)
                        .addComponent(bt_fix)
                        .addGap(18, 18, 18)
                        .addComponent(bt_dell)
                        .addGap(18, 18, 18)
                        .addComponent(bt_show)
                        .addGap(18, 18, 18)
                        .addComponent(btn_timkiem)
                        .addGap(18, 18, 18)
                        .addComponent(bt_exit_admin)
                        .addGap(30, 30, 30))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_id)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_msv)
                    .addComponent(txt_msv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_age)
                    .addComponent(txt_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_gender)
                    .addComponent(rd_boy)
                    .addComponent(rd_girl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_address))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_add)
                    .addComponent(bt_fix)
                    .addComponent(bt_dell)
                    .addComponent(bt_show)
                    .addComponent(btn_timkiem)
                    .addComponent(bt_exit_admin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.LINE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_addressActionPerformed

    private void bt_exit_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_exit_adminActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_bt_exit_adminActionPerformed

    private void bt_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_addActionPerformed
        if (!"".equals(txt_id.getText()) && !"".equals(txt_address.getText()) && !"".equals(txt_age.getText()) && !"".equals(txt_msv.getText()) && !"".equals(txt_name.getText())) {
            try {
                // TODO add your handling code here:
//            Class.forName(driver);
//            Connection conn = DriverManager.getConnection(url, user, password);
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                conn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=QLSinhVien;user=sa;password=123456");
                String sql = "insert into SinhVien values (?,?,?,?,?,?)";
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setString(1, txt_id.getText());
                ps.setString(2, txt_msv.getText());
                ps.setString(3, txt_name.getText());
                ps.setString(4, txt_age.getText());
                if (rd_boy.isSelected()) {
                    String boy = "Nam";
                    ps.setString(5, boy);
                } else if (rd_girl.isSelected()) {
                    String girl = "Nữ";
                    ps.setString(5, girl);
                } else {
                    ps.setString(5, buttonGroup1.getElements().toString());
                }
//            ps.setString(6, buttonGroup1.getElements().toString()); /// 
                ps.setString(6, txt_address.getText());

                int n = ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Thêm thành công sinh viên :" + txt_name.getText());

            } catch (Exception ex) {
                Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Vui long nhap du thong tin", "Không Hợp Lý!!!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bt_addActionPerformed

    private void bt_dellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_dellActionPerformed
        // TODO add your handling code here:

        if (txt_id.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Id cần xóa");
        } else {
            try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                conn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=QLSinhVien;user=sa;password=123456");
                String sql = "DELETE FROM SinhVien WHERE id=?";
                CallableStatement stm = conn.prepareCall(sql);
                stm.setString(1, txt_id.getText());
                stm.execute();
                JOptionPane.showMessageDialog(this, "Đã xóa thành công sinh viên : " + txt_id.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }
    }//GEN-LAST:event_bt_dellActionPerformed

    private void bt_fixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_fixActionPerformed
        // TODO add your handling code here:
        if (txt_id.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Id!!! ");
        } else if (txt_name.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Tên Sinh Viên!!! ");
        } else if (txt_address.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Địa Chỉ Sinh Viên!!! ");
        } else if (txt_age.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Ngày Sinh của Sinh Viên!!! ");
        } else if (buttonGroup1.getSelection().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Giới Tính của Sinh Viên!!! ");
        } else if (txt_msv.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Mã Sinh Viên!!! ");
        } else {
            try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                conn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=QLSinhVien;user=sa;password=123456");
                String sql = "update SinhVien set masinhvien=?, tensinhvien = ?, tuoisinhvien = ?, gioitinh = ?, diachi=?  where id = ?";
//                String sql = "update SinhVien values (?,?,?,?,?,?)";
                CallableStatement stm = conn.prepareCall(sql);
                Employee ep = new Employee();
                stm.setString(1, ep.getTenSinhVien());
                stm.setString(2, ep.getTuoiSinhVien());
                stm.setString(3, ep.getGioiTinh());
                stm.setString(4, ep.getMaSinhVien());
                stm.setString(5, ep.getDiaChi());
                stm.setString(6, ep.getId());
                stm.executeUpdate();
                ResultSet rs = stm.getGeneratedKeys();
                JOptionPane.showMessageDialog(this, "Sửa thành công " + ep.getId());
            } catch (Exception Ex) {
                JOptionPane.showMessageDialog(this, Ex);
            }
        }
    }//GEN-LAST:event_bt_fixActionPerformed

    private void bt_showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_showActionPerformed
        // TODO add your handling code here:
//        tb_main.removeAll();
//        String[] arr = {"ID", "Tên Sinh Viên", "Tuổi Sinh Viên", "Giới Tính", "Mã Sinh Viên", "Địa Chỉ"};
//        DefaultTableModel model = new DefaultTableModel(arr, 0);
        try {
            tb_main.removeAll();
//            String[] arr = {"ID", "Tên Sinh Viên", "Tuổi Sinh Viên", "Giới Tính", "Mã Sinh Viên", "Địa Chỉ"};
            DefaultTableModel model = (DefaultTableModel) tb_main.getModel();
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            conn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=QLSinhVien;user=sa;password=123456");
            String sql = "select * from SinhVien";
            PreparedStatement stm = conn.prepareStatement(sql);
            ResultSet rs = stm.executeQuery();

            while (rs.next()) {
                Vector vt = new Vector();
                vt.add(rs.getString("id"));
                vt.add(rs.getString("masinhvien"));
                vt.add(rs.getString("tensinhvien"));
                vt.add(rs.getString("tuoisinhvien"));
                vt.add(rs.getString("gioitinh"));
                vt.add(rs.getString("diachi"));
                model.addRow(vt);
            }
            System.out.print(rs.getString("diachi"));
            tb_main.setModel(model);

        } catch (Exception ex) {
//            JOptionPane.showMessageDialog(null, ex);
            System.out.println(ex);
        }
    }//GEN-LAST:event_bt_showActionPerformed

    private void none(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_none
        // TODO add your handling code here:
    }//GEN-LAST:event_none

    private void btn_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timkiemActionPerformed
//        try {
        // TODO add your handling code here:
        if (txt_id.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Id cần xóa");
        } else {
            try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                conn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=QLSinhVien;user=sa;password=123456");
                String sql = "SELECT * FROM SinhVien WHERE id LIKE ?";
                DefaultTableModel model = (DefaultTableModel) tb_main.getModel();
                CallableStatement stm = conn.prepareCall(sql);
                stm.setString(1, txt_id.getText());
                stm.execute();
                ResultSet rs = stm.executeQuery();
                if (rs.next()) {
                    Vector vt = new Vector();
                    vt.add(rs.getString("id"));
                    vt.add(rs.getString("masinhvien"));
                    vt.add(rs.getString("tensinhvien"));
                    vt.add(rs.getString("tuoisinhvien"));
                    vt.add(rs.getString("gioitinh"));
                    vt.add(rs.getString("diachi"));
                    model.addRow(vt);
                    JOptionPane.showMessageDialog(this, "Hiển Thị thành công Sinh viên có id là : " + txt_id.getText());
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }
//            tb_main.removeAll();
//            String[] arr = {"ID", "Tên Sinh Viên", "Tuổi Sinh Viên", "Giới Tính", "Mã Sinh Viên", "Địa Chỉ"};
//            DefaultTableModel model = (DefaultTableModel) tb_main.getModel();
//            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
//            conn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=QLSinhVien;user=sa;password=123456");
//            String sql = "SELECT * FROM SinhVien WHERE id LIKE ?";
//                java.sql.PreparedStatement stm = conn.prepareStatement(sql);
//                stm.setString(1, txt_id.getText());
//                ResultSet rs = stm.executeQuery();
//                if (rs.next()){
//                Vector vt = new Vector();
//                vt.add(rs.getString("id"));
//                vt.add(rs.getString("masinhvien"));
//                vt.add(rs.getString("tensinhvien"));
//                vt.add(rs.getString("tuoisinhvien"));
//                vt.add(rs.getString("gioitinh"));
//                vt.add(rs.getString("diachi"));
//                model.addRow(vt);
//                }
//        } catch (Exception ex) {
//            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_btn_timkiemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_add;
    private javax.swing.JButton bt_dell;
    private javax.swing.JButton bt_exit_admin;
    private javax.swing.JButton bt_fix;
    private javax.swing.JButton bt_show;
    private javax.swing.JButton btn_timkiem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_address;
    private javax.swing.JLabel lb_age;
    private javax.swing.JLabel lb_gender;
    private javax.swing.JLabel lb_id;
    private javax.swing.JLabel lb_msv;
    private javax.swing.JRadioButton rd_boy;
    private javax.swing.JRadioButton rd_girl;
    private javax.swing.JTable tb_main;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_age;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_msv;
    private javax.swing.JTextField txt_name;
    // End of variables declaration//GEN-END:variables
}
